In [2]:
import numpy as np

## Creating array

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.ones([2, 2], dtype=np.int)

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\2932237971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2, 2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [6]:
np.ones([3, 2], dtype=np.float)

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\2936883358.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3, 2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
X = np.arange(4, dtype=np.int)
np.ones_like(X)

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\3464803085.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

In [8]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int)
np.zeros_like(X)

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\3591324098.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones([4, 4], dtype=np.int) * 5

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\3814862606.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4, 4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
X = np.array([[2, 3], [6, 2]], dtype=np.int)
np.ones_like(X) * 7

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\2693832569.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[2, 3], [6, 2]], dtype=np.int)


array([[7, 7],
       [7, 7]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.randint(10, size=3)

array([6, 0, 4])

In [14]:
np.random.randn(3, 3, 3)

array([[[ 1.13748195,  0.04356246,  0.00819536],
        [ 0.07503322, -0.50613585, -0.84872518],
        [ 1.95647511, -1.16890293, -0.20079795]],

       [[ 0.32540609,  0.79689225, -0.44684277],
        [-1.28616145, -0.35065356, -2.25936732],
        [ 0.93433412,  1.43840384, -0.46339633]],

       [[ 1.04585513, -0.03046058, -1.03323306],
        [-1.62484007,  0.26610927, -1.94532173],
        [-0.01391825,  1.04398366,  0.92759061]]])

In [15]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [16]:
X = np.array([5, 2, 3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 2400455883440
[5 2 3] 2400455884304


C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\2744567037.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([5, 2, 3], dtype=np.int)


In [17]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
Z = np.zeros((10, 10))

print(f"{Z.size * Z.itemsize} bytes")

800 bytes


## Array indexation

In [23]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0]

'A'

In [24]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[-1]

'E'

In [25]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [27]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [28]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [29]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [30]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [31]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [32]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[0, 0]

1

In [33]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1]

16

In [34]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [35]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[:2, :2]

array([[1, 2],
       [5, 6]])

In [36]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

## Array manipulation

In [37]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

C:\Users\homindolentrahar\AppData\Local\Temp\ipykernel_9184\4247539020.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

In [38]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

In [39]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [40]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [42]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

In [43]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [44]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## Boolean arrays

In [45]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [46]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

In [47]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [48]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

## Logic functions

In [49]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [50]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

## Summary statistics

In [51]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

In [52]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.mean()

3.7

In [53]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [54]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=1)

array([10, 26, 42, 58])

In [55]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.max()

10